In [2]:
import numpy as np

## 1.1 Numpy属性

### 1.1.1 添加一个numpy数组

In [2]:
array = np.array([[1, 2, 3], [2, 3, 4]])
print(array)

[[1 2 3]
 [2 3 4]]


### 1.1.2 numpy的几种属性

In [5]:
print('number of dim:', array.ndim) # 维度

number of dim: 2


In [4]:
print('shape:', array.shape) # 行数和列数

shape: (2, 3)


In [6]:
print('size:', array.size) # 元素个数

size: 6


## 1.2 Numpy创建的array

### 1.2.1 创建数组

In [7]:
a = np.array([2, 23, 4]) # list 1d
print(a)

[ 2 23  4]


### 1.2.2 指定数据dtype

In [9]:
a = np.array([2, 23, 4], dtype=np.int64)
print(a.dtype)

int64


In [10]:
a = np.array([2, 23, 4], dtype=np.int32)
print(a.dtype)

int32


In [11]:
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)

float64


In [12]:
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


### 1.2.3 创建特定数据

In [13]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [15]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
a = np.ones((3, 4), dtype = np.int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
a = np.empty((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
a = np.arange(10, 20, 2)
print(a)

[10 12 14 16 18]


In [20]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a = np.linspace(1, 10, 20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [22]:
a = np.linspace(1, 10, 20).reshape((5, 4))
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


## 1.3 Numpy基础运算1

In [1]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.arange(4)

### 1.3.1 numpy的几种基本运算

In [2]:
c = a - b
print(c)

[10 19 28 37]


In [3]:
c = b**2
print(c)

[0 1 4 9]


In [4]:
c = 10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [5]:
print(b<3)

[ True  True  True False]


In [3]:
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [4]:
c_dot = np.dot(a, b)
print(c_dot)

[[2 4]
 [2 3]]


In [5]:
a = np.random.random((2, 4))
print(a)

[[0.1295809  0.03967375 0.1604812  0.3606796 ]
 [0.59150128 0.70922688 0.88216409 0.64169651]]


In [6]:
print(np.sum(a))

3.515004198156646


In [7]:
print(np.min(a))

0.03967374706084681


In [8]:
print(np.max(a))

0.8821640889674136


In [10]:
print("a = ", a)

a =  [[0.1295809  0.03967375 0.1604812  0.3606796 ]
 [0.59150128 0.70922688 0.88216409 0.64169651]]


In [11]:
print("sum = ", np.sum(a,axis=1))

sum =  [0.69041544 2.82458876]


In [12]:
print("min = ", np.min(a, axis=0))

min =  [0.1295809  0.03967375 0.1604812  0.3606796 ]


In [13]:
print("max = ", np.max(a, axis=1))

max =  [0.3606796  0.88216409]


## 1.4 Numpy 基础运算2

In [14]:
A = np.arange(2, 14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [15]:
print(np.argmin(A))

0


In [16]:
print(np.argmax(A))

11


### 1.4.1 numpy的几种基本运算

In [17]:
print(np.mean(A))
print(np.average(A))

7.5
7.5


In [18]:
print(A.mean())

7.5


In [21]:
print(np.median(A))

7.5


In [24]:
print(np.cumsum(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [25]:
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [29]:
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [31]:
print(np.transpose(A))
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [33]:
print(A)
print(np.clip(A, 5, 9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


## 1.5 Numpy 索引

### 1.5.1 一维索引

In [34]:
A = np.arange(3, 15)
print(A[3])

6


In [35]:
A = np.arange(3, 15).reshape((3, 4))
print(A[2])

[11 12 13 14]


### 1.5.2 二维索引

In [36]:
print(A[1][1])

8


In [37]:
print(A[1, 1])

8


In [38]:
print(A[1, 1:3])

[8 9]


In [39]:
print(A[1][1:3])

[8 9]


In [40]:
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [41]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [42]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [43]:
A = np.arange(3, 15).reshape((3, 4))
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [44]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


## 1.6 Numpy array 合并

### 1.6.1 np.vstack()

In [46]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
print(np.vstack((A, B)))

[[1 1 1]
 [2 2 2]]


In [48]:
C = np.vstack((A, B))
print(A.shape, C.shape)

(3,) (2, 3)


### 1.6.2 np.hstack()

In [50]:
D = np.hstack((A, B))
print(D)
print(A.shape, D.shape)

[1 1 1 2 2 2]
(3,) (6,)


### 1.6.3 np.newaxis()

In [54]:
print(A[np.newaxis, :])
print(A[np.newaxis, :].shape)
print(A[:, np.newaxis])
print(A[:, np.newaxis].shape)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [57]:
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]

C = np.vstack((A, B))
D = np.hstack((A, B))
print(C)
print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]


In [58]:
C = np.concatenate((A, B, B, A), axis = 0)
print(C)
D = np.concatenate((A, B, B, A), axis = 1)
print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


## 1.7 Numpy array 分割

### 1.7.1 创建数据

In [59]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 1.7.2 纵向分割

In [61]:
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### 1.7.3 横向分割

In [62]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


### 1.7.4 错误的分割

In [63]:
print(np.split(A, 3, axis=1))

ValueError: array split does not result in an equal division

### 1.7.5 不等量的分割

In [65]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


### 1.7.6 其他的分割方式

In [66]:
print(np.vsplit(A, 3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [67]:
print(np.hsplit(A, 2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


## 1.8 Numpy copy & deep copy

### 1.8.1 = 的赋值方式会带有关联性

In [68]:
a = np.arange(4)
b = a
c = a
d = b

In [69]:
a[0] = 11
print(a)

[11  1  2  3]


In [70]:
b is a
c is a
d is a

True

In [71]:
d[1:3] = [22, 33]
print(a)
print(b)
print(c)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


### 1.8.2 copy()的赋值方式没有关联性

In [72]:
b = a.copy()
print(b)
a[3] = 44
print(a)
print(b)

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
